FROM python:3.12-slim-bookworm
LABEL authors="hieu"

WORKDIR /chatbone

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN uv init --build-backend setuptools
RUN uv init ./datastore && rm -rf .datastore/*
RUN uv init ./utilities && rm -rf .utilities/*

COPY datastore ./datastore
COPY utilities ./utilities

RUN uv sync --package datastore
CMD ["uv","run", "datastore", "run", "--host","0.0.0.0","--port","8000" ]
