FROM python:3.12-slim-bookworm
LABEL authors="hieu"

WORKDIR /chatbone

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# For save workspaces
RUN uv init --build-backend setuptools
RUN uv init ./auth && rm -rf .auth/*
RUN uv init ./utilities && rm -rf .utilities/*

COPY auth ./auth
COPY utilities ./utilities

RUN uv sync --package auth
CMD ["uv","run", "auth","run","--host","0.0.0.0","--port", "8000"]
