# A generic, single database configuration.

[alembic]
databases = datastore_db, document_db

[DEFAULT]
;script_location = .
;prepend_sys_path = .
version_path_separator = os

[datastore_db]
;version_locations = ./datastore_db_version
env_file="../env.datastore"
drivername_env=DATASTORE_DB__DRIVERNAME
username_env=DATASTORE_DB__USERNAME
password_env=DATASTORE_DB__PASSWORD
host_env=DATASTORE_DB__HOST
port_env=DATASTORE_DB__PORT
database_env=DATASTORE_DB__DATABASE

;[document_db]
;version_locations = ./migrations/document_db

[post_write_hooks]


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
