[project]
name = "utilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hieu", email = "hieu.buinguyen2352001@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.13",
    "cryptography>=44.0.2",
    "fastapi[standard]==0.115.12",
    "loguru>=0.7.3",
    "miniopy-async>=1.23.0",
    "psutil>=7.0.0",
    "pwdlib[argon2]>=0.2.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "redis>=6.2.0",
    "setuptools>=80.9.0",
    "sqlalchemy[asyncio]>=2.0.38",
    "uuid7>=0.1.0",
]

[project.scripts]
utilities = "utilities:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
