max_sessions=10
max_messages=20
max_user_summaries=5
max_chat_summaries=5

[datastore_request_timeout]
default=5
#session_create = 5
#session_delete = 5
#message_create = 5
#message_get_latest = 5
#message_delete_old = 5
summary_create = 5
summary_get_latest = 5
summary_delete_old = 5

