"""Upgrade at 2025-07-06 16:31:48.900127+00:00

Revision ID: dfd4c25270d7
Revises: 2190a5ef98fd
Create Date: 2025-07-06 23:31:49.325481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd4c25270d7'
down_revision: Union[str, None] = '2190a5ef98fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
