# docker-compose.yml
# A simple Docker Compose file to run Redis Stack and PostgreSQL


services:
    # Service definition for Redis Stack
    redis-stack:
        image: redis/redis-stack:latest # Use the official Redis Stack image
        container_name: chat_redis # Optional: Assign a specific name to the container
        environment:
            REDIS_ARGS: "--requirepass 2352001 --user hieu"
        ports:
            - "3333:6379" # Map host port 6379 to container port 3333 (standard Redis)
            - "8001:8001" # Map host port 8001 to container port 8001 (RedisInsight UI)
        volumes:
            - redis_stack_data:/data # Mount a named volume to persist Redis data
        networks:
            - chatbone-network # Connect to the custom network

    # Service definition for PostgreSQL
    postgres:
        image: pgvector/pgvector:0.8.0-pg17 # Use the official PostgreSQL image
        container_name: chatbone_db # Optional: Assign a specific name to the container
        environment:
            # Set environment variables required by the Postgres image
            POSTGRES_USER: hieu # Define the default username
            POSTGRES_PASSWORD: 2352001 # Define the default password (change this in production!)
            POSTGRES_DB: datastore_db # Define the default database name to create
        ports:
            - "5432:5432" # Map host port 5432 to container port 5432 (standard PostgreSQL)
        volumes:
            - postgres_data:/var/lib/postgresql/data # Mount a named volume to persist PostgreSQL data
        networks:
            - chatbone-network # Connect to the custom network

    minio:
        image: minio/minio:latest
        container_name: chatbone_storage
        ports:
            - "9000:9000" # MinIO API
            - "9001:9001" # MinIO Console
        environment:
            MINIO_ROOT_USER: "hieu" # Replace with your desired username
            MINIO_ROOT_PASSWORD: "hieu2352001" # Replace with your desired password
            MINIO_REGION: ap-southeast-1
            MINIO_HTTP_TRACE: "stdout"
        volumes:
            - minio_data:/data # Persistent storage for MinIO
        networks:
            - chatbone-network
        command: server /data --console-address ":9001"
    
    auth:
        shm_size: '2gb'
        build:
            context: ../..
            dockerfile: deployments/auth/auth.Dockerfile
        image: auth-app:latest
        
        container_name: auth_app
        ports:
            - "23500:8000"
            - "23501:8265"
        environment:
            AUTH_DATASTORE__URL: "http://datastore:8000"
            AUTH_CONFIG__FILE: "./config.toml"
        
        command: ["uv","run", "uvicorn",
                  "--host","0.0.0.0",
                  "auth:app"]
        
        networks:
        - chatbone-network
        
        
    datastore:
        shm_size: '2gb'
        build:
            context: ../..
            dockerfile: deployments/datastore/datastore.Dockerfile
        image: datastore-app:latest
        container_name: datastore_app
        
        ports:
        - "23502:8000"
        - "23503:8265"
        environment:
            DATASTORE_DB__DRIVERNAME: 'postgresql+asyncpg'
            DATASTORE_DB__USERNAME: 'hieu'
            DATASTORE_DB__PASSWORD: '2352001'
            DATASTORE_DB__HOST: 'postgres'
            DATASTORE_DB__PORT: '5432'
            DATASTORE_DB__DATABASE: 'datastore_db'
            DATASTORE_CONFIG__FILE: './config.toml'
        
        command:  ["uv","run", "uvicorn",
                   "--host","0.0.0.0", # see : https://stackoverflow.com/questions/75040507/how-to-access-fastapi-backend-from-a-different-machine-ip-on-the-same-local-netw/75041731#75041731
                   "datastore:app"]
        
        networks:
        - chatbone-network


# Define named volumes for data persistence
volumes:
    redis_stack_data:
        driver: local # Use the local driver (default)
    postgres_data:
        driver: local # Use the local driver (default)
    minio_data:
        driver: local
# Define a custom network for the services to communicate
networks:
    chatbone-network:
        driver: bridge # Use the bridge driver (default)
